name: Test pull request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  release:
    name: Test pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean buildAndroid :patches:checkSafeXSmali

      - name: Upload Morphe patch bundle
        uses: actions/upload-artifact@v4
        with:
          name: safex-piko-mpp
          path: patches/build/libs/patches-*.mpp
          if-no-files-found: error
